version: '3.8'

services:
  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    depends_on:
      - output

  indexer:
    build:
      context: ./src/indexer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env

  subject_space:
    build:
      context: ./src/subject_space
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - STATUS_ENDPOINT=http://indexer:8081
    depends_on:
      - indexer

  output:
    build:
      context: ./src/output
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      - SUBJECT_SPACE_ENDPOINT=http://subject_space:8082
    depends_on:
      - subject_space

  note_indexer:
    build:
      context: ./src/note_indexer
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - STATUS_ENDPOINT=http://indexer:8081
    depends_on:
      - indexer

  pdf_indexer:
    build:
      context: ./src/pdf_indexer
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - STATUS_ENDPOINT=http://indexer:8081
    depends_on:
      - indexer

  website_indexer:
    build:
      context: ./src/website_indexer
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - STATUS_ENDPOINT=http://indexer:8081
    depends_on:
      - indexer

  podcast:
    build:
      context: ./src/podcast_generator
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SUBJECT_SPACE_ENDPOINT=http://subject_space:8082
      - OUTPUT_STATUS_ENDPOINT=http://output:8083
    depends_on:
      - output

networks:
  default:
    driver: bridge